### ISSUE TITLE
Not compatible with GymFC

### ISSUE THREAD

**Issue by Yan-Wang747** [wil3/gymfc-aircraft-plugins#2]
Hello,

I compiled the source codes. But the build folder doesn't contain the required file "libAircraftConfigPlugin.so". Is it renamed to something else?

Thanks,

**Comment by wil3** [comment]
Hi sorry for the delay I don't remember getting alerted. 

The libAircraftConfigPlugin plugin is part of GymFC, you can find them here, https://github.com/wil3/gymfc/tree/master/gymfc/envs/assets/gazebo/plugins
