### ISSUE TITLE
Error while generating .so files

### ISSUE THREAD

**Issue by Pranav-India** [wil3/gymfc-aircraft-plugins#3]
Hi @wil3 

I have written both the files for the distance sensor .cpp and .h 
Now to generate the .so file I need to compile the file but when I run the command 
`gcc -c -o `

 for the compilation it is giving the following error:

**In file included from gazebo_distance_plugin.cpp:21:0:
gazebo_distance_plugin.h:22:10: fatal error: Eigen/Core: No such file or directory
#include <Eigen/Core>
          ^~~~~~~~~~~~
compilation terminated.** 

so I found the Eigen folder and copied the Core in the same dictionary I had to do this for all the .hh files, I copied them from gazebo folder(in /usr) to the current directory but now I got 

**In file included from common.hh:5:0,
                 from gazebo_distance_plugin.h:23:
gazebo/common/Animation.hh:22:10: fatal error: ignition/math/Spline.hh: No such file or directory
 #include <ignition/math/Spline.hh>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated."**

so I assume that coping the .hh files is not going to help. 
Do I need to save the files in a particular directory and there run these commands?

**Comment by wil3** [comment]
Please follow the build instructions specified in the readme. This project uses cmake.
